//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t cancel a reservation less than 24 hours before check-in..
        /// </summary>
        internal static string _24H {
            get {
                return ResourceManager.GetString("24H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only leave a review 5 days after checkout.
        /// </summary>
        internal static string _5Days {
            get {
                return ResourceManager.GetString("5Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodations.
        /// </summary>
        internal static string AccommodationsText {
            get {
                return ResourceManager.GetString("AccommodationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        internal static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reviewed this reservation..
        /// </summary>
        internal static string AlrReviewed {
            get {
                return ResourceManager.GetString("AlrReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wherever/Whenever.
        /// </summary>
        internal static string AnywhereText {
            get {
                return ResourceManager.GetString("AnywhereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select dates..
        /// </summary>
        internal static string au1 {
            get {
                return ResourceManager.GetString("au1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of guests..
        /// </summary>
        internal static string au2 {
            get {
                return ResourceManager.GetString("au2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if check in and check out dates are correct..
        /// </summary>
        internal static string au3 {
            get {
                return ResourceManager.GetString("au3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum days you can book this accommodation for is .
        /// </summary>
        internal static string au4 {
            get {
                return ResourceManager.GetString("au4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days..
        /// </summary>
        internal static string au5 {
            get {
                return ResourceManager.GetString("au5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available accommodations.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating.
        /// </summary>
        internal static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reservation.
        /// </summary>
        internal static string CancelRes {
            get {
                return ResourceManager.GetString("CancelRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t cancel a reservation that is in progress..
        /// </summary>
        internal static string CancelResProg {
            get {
                return ResourceManager.GetString("CancelResProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this reservation?.
        /// </summary>
        internal static string CancelResQ {
            get {
                return ResourceManager.GetString("CancelResQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully canceled reservation!.
        /// </summary>
        internal static string CancelSucc {
            get {
                return ResourceManager.GetString("CancelSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in:.
        /// </summary>
        internal static string Checkin {
            get {
                return ResourceManager.GetString("Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out:.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one of the  available dates to make a reservation.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose desired period to find available dates:.
        /// </summary>
        internal static string ChosePeriod {
            get {
                return ResourceManager.GetString("ChosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityW {
            get {
                return ResourceManager.GetString("CityW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness:.
        /// </summary>
        internal static string Cleanliness {
            get {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseBtn {
            get {
                return ResourceManager.GetString("CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Forum.
        /// </summary>
        internal static string CloseForum {
            get {
                return ResourceManager.GetString("CloseForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentBtn {
            get {
                return ResourceManager.GetString("CommentBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while sending the request..
        /// </summary>
        internal static string CommentError {
            get {
                return ResourceManager.GetString("CommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string CountryW {
            get {
                return ResourceManager.GetString("CountryW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Check in:.
        /// </summary>
        internal static string CurrentCheckin {
            get {
                return ResourceManager.GetString("CurrentCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Check out:.
        /// </summary>
        internal static string CurrentCheckout {
            get {
                return ResourceManager.GetString("CurrentCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many days are you staying?.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string DaysWatermark {
            get {
                return ResourceManager.GetString("DaysWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsBtn {
            get {
                return ResourceManager.GetString("DetailsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give accommodation a rating..
        /// </summary>
        internal static string EmptyCleanliness {
            get {
                return ResourceManager.GetString("EmptyCleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required..
        /// </summary>
        internal static string EmptyComm {
            get {
                return ResourceManager.GetString("EmptyComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be empty!.
        /// </summary>
        internal static string EmptyComment {
            get {
                return ResourceManager.GetString("EmptyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required..
        /// </summary>
        internal static string EmptyLoc {
            get {
                return ResourceManager.GetString("EmptyLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the owner..
        /// </summary>
        internal static string EmptyOwnerRating {
            get {
                return ResourceManager.GetString("EmptyOwnerRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question cannot be empty..
        /// </summary>
        internal static string EmptyQuestion {
            get {
                return ResourceManager.GetString("EmptyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        internal static string ExportToPdf {
            get {
                return ResourceManager.GetString("ExportToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum created! Would you like to view the forum?.
        /// </summary>
        internal static string ForumAdded {
            get {
                return ResourceManager.GetString("ForumAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Closed.
        /// </summary>
        internal static string ForumClosed {
            get {
                return ResourceManager.GetString("ForumClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum is already closed.
        /// </summary>
        internal static string ForumClosedAlr {
            get {
                return ResourceManager.GetString("ForumClosedAlr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want close this forum?.
        /// </summary>
        internal static string ForumQ {
            get {
                return ResourceManager.GetString("ForumQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string ForumsLink {
            get {
                return ResourceManager.GetString("ForumsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Created!.
        /// </summary>
        internal static string ForumSuccess {
            get {
                return ResourceManager.GetString("ForumSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give owner and property a rating.
        /// </summary>
        internal static string GiveRating {
            get {
                return ResourceManager.GetString("GiveRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        internal static string GuestNumText {
            get {
                return ResourceManager.GetString("GuestNumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many guests are coming?.
        /// </summary>
        internal static string Guests {
            get {
                return ResourceManager.GetString("Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        internal static string GuestWatermark {
            get {
                return ResourceManager.GetString("GuestWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeLink {
            get {
                return ResourceManager.GetString("HomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        internal static string HostText {
            get {
                return ResourceManager.GetString("HostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t change the dates.
        /// </summary>
        internal static string inv1 {
            get {
                return ResourceManager.GetString("inv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dates.
        /// </summary>
        internal static string inv2 {
            get {
                return ResourceManager.GetString("inv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageBtn {
            get {
                return ResourceManager.GetString("LanguageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave a comment.
        /// </summary>
        internal static string LeaveComm {
            get {
                return ResourceManager.GetString("LeaveComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string LightModeText {
            get {
                return ResourceManager.GetString("LightModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationWatermark {
            get {
                return ResourceManager.GetString("LocationWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make A Reservation.
        /// </summary>
        internal static string MakeReservation {
            get {
                return ResourceManager.GetString("MakeReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of guests:.
        /// </summary>
        internal static string MaxGuestText {
            get {
                return ResourceManager.GetString("MaxGuestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string ModeText {
            get {
                return ResourceManager.GetString("ModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and Surname:.
        /// </summary>
        internal static string NameSurname {
            get {
                return ResourceManager.GetString("NameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameWatermark {
            get {
                return ResourceManager.GetString("NameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Check in:.
        /// </summary>
        internal static string NewCheckin {
            get {
                return ResourceManager.GetString("NewCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Check Out:.
        /// </summary>
        internal static string NewCheckout {
            get {
                return ResourceManager.GetString("NewCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string NewDates {
            get {
                return ResourceManager.GetString("NewDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available dates for selected period.
        /// </summary>
        internal static string NoAvailableDates {
            get {
                return ResourceManager.GetString("NoAvailableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotReviewed.
        /// </summary>
        internal static string NotReviewed {
            get {
                return ResourceManager.GetString("NotReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other forums.
        /// </summary>
        internal static string OtherForum {
            get {
                return ResourceManager.GetString("OtherForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners coment:.
        /// </summary>
        internal static string OwnersC {
            get {
                return ResourceManager.GetString("OwnersC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners answer:.
        /// </summary>
        internal static string OwnersComm {
            get {
                return ResourceManager.GetString("OwnersComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past vacations.
        /// </summary>
        internal static string Past {
            get {
                return ResourceManager.GetString("Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number:.
        /// </summary>
        internal static string PhoneNum {
            get {
                return ResourceManager.GetString("PhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string PostBtn {
            get {
                return ResourceManager.GetString("PostBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileLink {
            get {
                return ResourceManager.GetString("ProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate the owner and the property.
        /// </summary>
        internal static string RateOwnandProp {
            get {
                return ResourceManager.GetString("RateOwnandProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t cancel a reservation less than .
        /// </summary>
        internal static string ref1 {
            get {
                return ResourceManager.GetString("ref1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days before check-in..
        /// </summary>
        internal static string ref2 {
            get {
                return ResourceManager.GetString("ref2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation recommendation.
        /// </summary>
        internal static string RenovationR {
            get {
                return ResourceManager.GetString("RenovationR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent!.
        /// </summary>
        internal static string ReqSent {
            get {
                return ResourceManager.GetString("ReqSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request rescheduling.
        /// </summary>
        internal static string RequestBtn {
            get {
                return ResourceManager.GetString("RequestBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required!.
        /// </summary>
        internal static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule your reservation.
        /// </summary>
        internal static string RescheduleHead {
            get {
                return ResourceManager.GetString("RescheduleHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t reschedule past reservations..
        /// </summary>
        internal static string ReschPast {
            get {
                return ResourceManager.GetString("ReschPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation rescheduling requests.
        /// </summary>
        internal static string ReservationReq {
            get {
                return ResourceManager.GetString("ReservationReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescheduling request details.
        /// </summary>
        internal static string ReservationReqDet {
            get {
                return ResourceManager.GetString("ReservationReqDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        internal static string ReservationsLink {
            get {
                return ResourceManager.GetString("ReservationsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Successful!.
        /// </summary>
        internal static string ReservationSuccessful {
            get {
                return ResourceManager.GetString("ReservationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string ReserveBtn {
            get {
                return ResourceManager.GetString("ReserveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string rev {
            get {
                return ResourceManager.GetString("rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Details.
        /// </summary>
        internal static string revDet {
            get {
                return ResourceManager.GetString("revDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string ReviewBtn {
            get {
                return ResourceManager.GetString("ReviewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed.
        /// </summary>
        internal static string Reviewed {
            get {
                return ResourceManager.GetString("Reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while submitting review.
        /// </summary>
        internal static string ReviewErr {
            get {
                return ResourceManager.GetString("ReviewErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully submited the review!.
        /// </summary>
        internal static string ReviewSucc {
            get {
                return ResourceManager.GetString("ReviewSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Following:.
        /// </summary>
        internal static string RuleF {
            get {
                return ResourceManager.GetString("RuleF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for accommodations.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new dates.
        /// </summary>
        internal static string SelectNewDates {
            get {
                return ResourceManager.GetString("SelectNewDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Rescheduling Request.
        /// </summary>
        internal static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new forum.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitBtn {
            get {
                return ResourceManager.GetString("SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful reservation for.
        /// </summary>
        internal static string SuccessfulReservation {
            get {
                return ResourceManager.GetString("SuccessfulReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Become Super Guest you need to have at least 10 reservations in the past year..
        /// </summary>
        internal static string SuperG {
            get {
                return ResourceManager.GetString("SuperG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Guest.
        /// </summary>
        internal static string SuperGuest {
            get {
                return ResourceManager.GetString("SuperGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write title of the forum.
        /// </summary>
        internal static string TitleW {
            get {
                return ResourceManager.GetString("TitleW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeWatermark {
            get {
                return ResourceManager.GetString("TypeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming vacations.
        /// </summary>
        internal static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select urgency level.
        /// </summary>
        internal static string Urgency {
            get {
                return ResourceManager.GetString("Urgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This forums has been labeled as very useful.
        /// </summary>
        internal static string UsefulFor {
            get {
                return ResourceManager.GetString("UsefulFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewBtn {
            get {
                return ResourceManager.GetString("ViewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to view the reservation?.
        /// </summary>
        internal static string ViewReservationPrompt {
            get {
                return ResourceManager.GetString("ViewReservationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has visited the location from this forum.
        /// </summary>
        internal static string VisitedComm {
            get {
                return ResourceManager.GetString("VisitedComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for any accommodation available in chosen time period.
        /// </summary>
        internal static string WheneverSearch {
            get {
                return ResourceManager.GetString("WheneverSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a new comment.
        /// </summary>
        internal static string WriteComm {
            get {
                return ResourceManager.GetString("WriteComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a question you have about the location.
        /// </summary>
        internal static string WriteQuest {
            get {
                return ResourceManager.GetString("WriteQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your forums.
        /// </summary>
        internal static string YourForum {
            get {
                return ResourceManager.GetString("YourForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information:.
        /// </summary>
        internal static string YourInfo {
            get {
                return ResourceManager.GetString("YourInfo", resourceCulture);
            }
        }
    }
}
